package web3g

const (
	Web3ClientVersion = "web3_clientVersion"
	Web3Sha3          = "web3_sha3"

	NetVersion        = "net_version"
	NetListening      = "net_listening"
	NetPeerCount      = "net_peerCount"

	PlatonProtocolVersion = "platon_protocolVersion"
	PlatonSyncing         = "platon_syncing"
	PlatonGasPrice        = "platon_gasPrice"
	PlatonAccounts        = "platon_accounts"
	PlatonBlockNumber     = "platon_blockNumber"
	PlatonGetBalance      = "platon_getBalance"
	PlatonGetStorageAt    = "platon_getStorageAt"
	PlatonGetCode         = "platon_getCode"
	PlatonSign            = "platon_sign"
	PlatonGetTransactionCount = "platon_getTransactionCount"
	PlatonGetBlockTransactionCountByHash = "platon_getBlockTransactionCountByHash"
	PlatonGetBlockTransactionCountByNumber = "platon_getBlockTransactionCountByNumber"
	PlatonSendTransaction = "platon_sendTransaction"
	PlatonSendRawTransaction = "platon_sendRawTransaction"
	PlatonCall            = "platon_call"
	PlatonEstimateGas     = "platon_estimateGas"
	PlatonGetBlockByHash  = "platon_getBlockByHash"
	PlatonGetBlockByNumber= "platon_getBlockByNumber"
	PlatonGetTransactionByHash = "platon_getTransactionByHash"
	PlatonGetTransactionByBlockHashAndIndex = "platon_getTransactionByBlockHashAndIndex"
	PlatonGetTransactionByBlockNumberAndIndex = "platon_getTransactionByBlockNumberAndIndex"
	PlatonGetTransactionReceipt = "platon_getTransactionReceipt"
	PlatonNewFilter = "platon_newFilter"
	PlatonNewBlockFilter = "platon_newBlockFilter"
	PlatonNewPendingTransactionFilter = "platon_newPendingTransactionFilter"
	PlatonUninstallFilter = "platon_uninstallFilter"
)
